### ISSUE TITLE
gmrender segfaults when trying to run it on an alpine linux installation

### ISSUE THREAD

**Issue by AryToNeX** [hzeller/gmrender-resurrect#201]
GDB output

```
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gmediarender...
(gdb) run
Starting program: /usr/local/bin/gmediarender
gmediarender 0.0.8 started [ gmediarender 0.0.8_git2020-01-09_26d8f7e (libupnp-1.8.4; glib-2.62.4; gstreamer-1.16.2) ].
Logging switched off. Enable with --logfile=<filename> (or --logfile=stdout for console)
[New LWP 16245]

Thread 1 "gmediarender" received signal SIGSEGV, Segmentation fault.
0x00007ffff7fbba4a in pthread_timedjoin_np () from /lib/ld-musl-x86_64.so.1
```

I needed this to run to achieve a headless audio server with speakers all across my house.. this is bugging me

**Comment by hzeller** [comment]
what is the output of gdb when you type `bt` after the crash? The stacktrace will help narrowing it down.

**Comment by AryToNeX** [comment]
```
naomi@naomi-server:~/Sorgenti$ gdb gmediarender
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gmediarender...
(gdb) run
Starting program: /usr/local/bin/gmediarender
gmediarender 0.0.8 started [ gmediarender 0.0.8_git2020-01-09_26d8f7e (libupnp-1.8.4; glib-2.62.4; gstreamer-1.16.2) ].
Logging switched off. Enable with --logfile=<filename> (or --logfile=stdout for console)
[New LWP 24856]

Thread 1 "gmediarender" received signal SIGSEGV, Segmentation fault.
0x00007ffff7fbba4a in pthread_timedjoin_np () from /lib/ld-musl-x86_64.so.1
(gdb) bt
#0  0x00007ffff7fbba4a in pthread_timedjoin_np () at /lib/ld-musl-x86_64.so.1
#1  0x0000000000000000 in  ()
```

**Comment by AryToNeX** [comment]
So, the problem was with the Portable UPnP library. Apparently, compiling version 1.8.6 from source fixed this issue,
