### ISSUE TITLE
gmediarender 0.0.7-git crashing on startup

### ISSUE THREAD

**Issue by anmith** [hzeller/gmrender-resurrect#74]
Hi,

I'm running an Raspberry Pi using Arch Linux.

After upgrading my Raspberry which was running fine since August, gmediarender crashes after "Registering support for 'application/x-ogg-avi'" with a segmentation fault / core dump.

I installed base-devel, cloned the git repository and compiled the binary according to the steps described at https://github.com/hzeller/gmrender-resurrect/blob/master/INSTALL.md

However, when running the new compiled version using src/gmediarender -f "My Renderer" it still crashes.

INFO [2014-12-18 15:45:02.189011 | main] gmediarender 0.0.7-git log started [ gmediarender 2014-03-01_61f5a8f (libupnp-1.6.19; glib-2.42.1; gstreamer-1.4.4) ]

Any ideas?

**Comment by MichaelSp** [comment]
same here
```
[...]
INFO  [2015-01-03 15:16:56.624252 | connmgr] Registering support for 'application/x-kate'
INFO  [2015-01-03 15:16:56.700734 | connmgr] Registering support for 'audio/x-wavpack'
INFO  [2015-01-03 15:16:56.859233 | connmgr] Registering support for 'application/x-hls'
INFO  [2015-01-03 15:16:56.902785 | connmgr] Registering support for 'audio/x-vorbis'
Segmentation fault
```

**Comment by hzeller** [comment]
I suspect a problem in the compilation of gstreamer. Often this is due to mismatching floating point compilation modes (using software emulation or hardware; some ARM cpus don't have all fp-commands).

Can you create a stack-trace of when this happens (gdb, command 'bt').

**Comment by MichaelSp** [comment]
Here is the stack-trace. 
```
>gdb gmediarender 
GNU gdb (Raspbian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gmediarender...done.
(gdb) run
Starting program: /usr/local/bin/gmediarender 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
gmediarender 0.0.7-git started [ gmediarender 2014-03-01_61f5a8f (libupnp-1.6.19+git20141001; glib-2.42.1; gstreamer-1.4.4) ].
Logging switched off. Enable with --logfile=<filename> (e.g. --logfile=/dev/stdout for console)


Program received signal SIGSEGV, Segmentation fault.
strchr () at ../ports/sysdeps/arm/armv6/strchr.S:28
28      ../ports/sysdeps/arm/armv6/strchr.S: No such file or directory.
(gdb) 
(gdb) bt
#0  strchr () at ../ports/sysdeps/arm/armv6/strchr.S:28
#1  0xb6d608d8 in g_param_spec_pool_lookup () from /usr/lib/arm-linux-gnueabihf/libgobject-2.0.so.0
#2  0xb6d5b6a4 in g_object_set_valist () from /usr/lib/arm-linux-gnueabihf/libgobject-2.0.so.0
#3  0xb6d5c00c in g_object_set () from /usr/lib/arm-linux-gnueabihf/libgobject-2.0.so.0
Cannot access memory at address 0x140
#4  0xb31fc110 in ?? () from /usr/lib/arm-linux-gnueabihf/gstreamer-1.0/libgstdvb.so
Cannot access memory at address 0x140
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```
I don't get it.

**Comment by MichaelSp** [comment]
Is there something else I can do to support you?

**Comment by anmith** [comment]
After performing a system update this morning, gmrender-resurrect works without crashing (again).
